[workspace]
members = ["makura", "makura_cli", "makura/fuzz"]
resolver = "3"

[workspace.package]
repository = "https://github.com/uraneko/makura"
license = "MIT"
edition = "2024"
# MSRV
rust-version = "1.85.0"

