[package]
name = "makura_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "maku"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
makura = { version = "0.1.2", path = "../makura" }
