name: Cargo Build - Test - Doc

on:
  push:
  workflow_dispatch: 

env: 
  CARGO_TERM_COLOR: always
  msrv: 1.85.0

jobs:
  build_test_doc:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target:
         # - x86_64-apple-darwin
         # - aarch64-apple-darwin
         # - aarch64-apple-ios
         # - x86_64-pc-windows-msvc
         # - x86_64-pc-windows-gnu
         - x86_64-unknown-linux-gnu
         # - x86_64-unknown-linux-musl
         # - aarch64-unknown-linux-gnu
         # - aarch64-unknown-linux-musl
         # - aarch64-linux-android 
    steps:
      - uses: actions/checkout@v4
      # - uses: dtolnay/rust-toolchain@stable
      #   with:
          # toolchain: $msrv   
          # targets: ${{ matrix.target }}
          # components: clippy
      - run: rustup default $msrv
      - run: rustup component add clippy
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --verbose --target ${{ matrix.target }}
      - run: cargo clippy --verbose
      - run: cargo test --verbose
      - run: cargo +nightly test --all-features
      - run: cargo +nightly doc --open
      
  

